### PR TITLE
Feature/fargate real

### PR DESCRIPTION
**Pull request by aochsner**
Split loadbalancer config and ecs/app config 

Integrated fargate changes & tested w/ EC2

Still need to actually test Fargate but EC2 works
remove APPLICATION_DATABASE_PASSWORD that's app specific
set EC2/Fargate choice in SSM

### CODE REVIEW

**Comment by aochsner** [comment]
not entirely sure why i split app into 2 nested stacks (1 loadbalancer config related, 1 ecs related)...makes logical sense but not strictly necessary.  thought i might need to have separate stacks between ec2 and fargate but turned out not to be the case

**Comment by aochsner** [comment]
I also made some changes straight to master that split out the EC2 hosts in the compute stack.  https://github.com/buildit/digitalrig-metal-aws/commit/e4e7189fd7d4738c18e1f3531d8b371e21b433aa

**Comment by aochsner** [comment]
Here's a diff of the key changes from my previous branch that got applied here https://github.com/buildit/bookit-infrastructure/compare/b009e4007a3b4386f1bcb131602ea0ec78498e57...fargate

**Comment by mjbuildit** [comment]
Mike Jett [2:19 PM]
The problem is that when you broke it out into separate templates, the Transform::Include references the individual templates in S3.  However, the individual templates are not what trigger the build pipeline...that's templates.zip.  So a developer could upload a new templates.zip, one in which there are changes both to main.yaml and app.yaml, but then when the new main.yaml were to be loaded, it would still pull in the older app.yaml from S3 which exists outside of the zip artifact

I don't see any real way to remediate that besides going back, because CloudFormation does not allow a child template to be pulled in from a zip file.  Unless we defined our own Import macro to hande this

Andy Ochsner [2:24 PM]
well, we push the templates and the zip as part of `upload-app`… maybe i’m missing something

Mike Jett [2:27 PM]
For the initial deploy from the makefile, it's not a problem.  The problem is trying to push any kind of configuration change.
On the older version, before I even got into the whole separation of pipelines thing, I could still just drop a templates.zip in the bucket to push a config change.

Andy Ochsner [2:36 PM]
hang on maybe i’m still confused…
push a templates.zip…that triggers the build
ah, but you’re saying there’s sort of a break in teh relationship between whats in s3 and whats in the zip… and even though it probably works you have to still do both and that’s a bit kludgy
?
or is there something more sniister
either way, it’s a good enough reason for me to put it back into the 1 template/stack

Mike Jett [2:40 PM]
That is correct...there could be a difference between what's inside the zip, and what's outside...and the relationship would not be immediately obvious to anyone else using it.

The only way to be sure of a sane config would be to FIRST upload the templates outside of the zip THEN upload the zip with all the same templates.

In the previous iteration of this, the app.yaml outside of the zip had no bearing on anything after the initial deploy.  But now, they get referenced every time main.yaml gets deployed

**Comment by aochsner** [comment]
Thanks for the feedback.  Updated to combine into 1

**Pull request merged**
